#' basic_BM_comps_mult_cross.R
#'
#' @description Function to compare spatial biomass estimates generated by Matlab,, but comparing the
#' #the age-1+ and age-2+ methods.  This will really only be appropriate for age-2+ fish.
#' Right now only does the spatial comparison. This script looks on a case by case basis
#' to see what the spatial differences are in biomass depending on age-2+ or full age (age-1+) methods
#'
#'
#' @param SurveyName - name of survey
#' @param DirNameFile excel file - contains paths and locations of files. Uses
#'  Export_dir as the directory that the exported files are in.
#' @param imagedir  - the directory for the images files to be placed in
#' @param cases - is the set of cases to be compared
#' @param hakeflagin adult hake (hakeflag=2), not filtering for hake (hakeflag=-1), age-0 hake (hakeflag=0), age-1 hake only (hakeflag=1), all hake (hakeflag=3), age-1+ (hakeflag=4). Passing this although assuming this will be hakeflag=1
#' @param yearin is the year that is being investigated

#' @examples
#'  \dontrun{
#' T<-basic_BM_comps_mult_cross<-function(SurveyNamein,DirNameFilein,imagedirin, cases,hakeflagin, yearin)
#' }
#' @export

#I want for reach case to be able to look at and see what the differences are in biomass depending on age-2+ or full age (age-1+) methods

basic_BM_comps_mult_cross<-function(SurveyNamein,DirNameFilein,imagedirin, cases,hakeflagin, yearin,...){
     year<-yearin
     # TotBio<-vector(length=length(cases))
     # KBoutlist<-vector(length=length(cases))
     # Per_diff<-vector(length=length(cases))
     # for (k in (1:length(cases))){
     #      KBoutlist[k]<-read_proc_reports(SurveyNamein, DirNameFilein,cases[[k]],hakeflag=hakeflagin) #kriged biomass outsputs
     #      #KBout<-read_proc_reports(SurveyNamein, DirNameFilein,case1in,age1flag=age1flagin) #kriged biomass outsputs for case 1
     #      #KBout2<-read_proc_reports(SurveyNamein, DirNameFilein,case2in,age1flag=age1flagin)
     #      ## Make table of NASC and differences
     #      TotBio[k]<-as.numeric(KBoutlist[[k]])
     #      Per_diff[k]=round((TotBio[k]-TotBio[1])*100/TotBio[1],5)  #round to 5 decimal places.  Compare to first case, assuming it is "original"
     # }
     # #TotBiotable<-data.frame(year,TotBio,Per_diff)
     # TotBiotable<-data.frame(year,rbind(TotBio,Per_diff))
     # #row.names(TotBiotable)<-c("Biomass","Percent difference")
     # TotBiotable<-cbind(c("Biomass","Percent difference"),TotBiotable)
     # colnames(TotBiotable)<-c("value","year",cases)
     # ftTotBio<-flextable::flextable(TotBiotable)
     # #ftTotBio<-flextable::set_header_labels(ftTotBio,TotBio.1.=case1in,TotBio.2.=case2in, Per_diff="Percent Difference")
     # #ftTotBio<-flextable::set_header_labels(ftTotBio,c(year,cases))
     # saveRDS(ftTotBio,file.path(imagedirin,paste0(yearin,"_export_BM_table", hakeflagin)))
     #
     # ## make a table of the difference in spatial unkriged
     uKSpBoutlist1<-list()
     uKSpBoutlist2<-list()
     uKSpBoutlist_diff<-list()

     for (k in (1:length(cases))){
          #read in the #age-2 biomass from age-1+ methods
          temp1<-Read_Spat_Unkriged_Reports_cross(cases[[k]], year, projpathbase,estimflag=4,hakeflag=hakeflagin) #kriged biomass outsputs
          temp1[]=lapply(temp1, as.numeric)
          uKSpBoutlist1[[k]]<-temp1
          # read in the age-2 biomass from age-2+ methods
          temp2<-read_spat_unkriged_reports(SurveyNamein, DirNameFilein,sheet=cases[[k]],hakeflag=hakeflagin) #kriged biomass outsputs
          temp2[]=lapply(temp2, as.numeric)
          uKSpBoutlist2[[k]]<-temp2
          uKSpBoutlist_diff[[k]]<- uKSpBoutlist2[[k]]
          uKSpBoutlist_diff[[k]]$Age1pM<-uKSpBoutlist1[[k]]$Agesum
          uKSpBoutlist_diff[[k]]<-dplyr::rename(uKSpBoutlist_diff[[k]],s.2=stratum)
          uKSpBoutlist_diff[[k]]$s.1<-uKSpBoutlist1[[k]]$stratum
          uKSpBoutlist_diff[[k]]$diff<-uKSpBoutlist1[[k]]$Agesum-uKSpBoutlist2[[k]]$Agesum  #difference
          uKSpBoutlist_diff[[k]]<-uKSpBoutlist_diff[[k]][,-5]  #get rid of wgt_total column
          uKSpBoutlist_diff_names<-names(uKSpBoutlist_diff[[k]])
          uKSpBoutlist_diff_names[5]<-"Age2pM"  #change Agesum (which is age-2 fish from age-2p methods into Age2pM name
          names(uKSpBoutlist_diff[[k]])<-uKSpBoutlist_diff_names  #rename for consistency

     }

     Sumdiffout<-uKSpBoutlist_diff[[1]]
     Sumdiffout<-Sumdiffout[,c(1:4)]
     basecase<-uKSpBoutlist_diff[[1]]$Age2pM  #age2+ numbers original age2+ methods
     Sumdiffout$original_bm<-basecase
     ## Look at age2+ outputs with age1+ methods for each case vs. original age2+ methods:
     for (k in (2:length(cases))){
          Sumdiffout<-merge(Sumdiffout,uKSpBoutlist_diff[[k]][,c(1:7)],by=c("Transect","Lat","Lon"),all=TRUE) #outer join
          #so s2.x here will be basecase (original)  s2.x will be original stratum for age-2+ method
          #s2.y will be the second case (e.g. region updated) for age-2+ method.  s.1 will be the age-1 method for the second
          #case (e.g region updated)
          #uKSpBout[is.na(uKSpBout)] <- 0 #change Nans to 0.
          colnames(Sumdiffout)[colnames(Sumdiffout)=='Age2pM']<-paste0(cases[[k]],'_2pM')
          colnames(Sumdiffout)[colnames(Sumdiffout)=='Age1pM']<-paste0(cases[[k]],'_1pM')
          #uKSpBout[,cases[[k]]]<-uKSpBoutlist[[k]][,c(6)] #get biomass for other cases
          Sumdiffout[,paste0(cases[[k]],'_1pM')]<-Sumdiffout[,paste0(cases[[k]],'_1pM')]-Sumdiffout$original_bm
          Sumdiffout[,paste0(cases[[k]],'_2pM')]<-Sumdiffout[,paste0(cases[[k]],'_2pM')]-Sumdiffout$original_bm
     }

     # uKSpBoutlist_diff is a list of 3 cases, with a table for each case
     # I think this enough for what I need

     ## Below doesn't work, is from basic_BM_comps_mult
    #  uKSpBoutlist_diff<-lapply(uKSpBoutlist_diff,round,digits=3) #need round early so that lat longs will match
    #  uKSpBout<-uKSpBoutlist[[1]][,c(1:5)] #keep metadata, using that for first case
    #  uKSpBout[]<-lapply(uKSpBout,as.numeric)
    #  uKSpBout[,cases[[1]]]<-uKSpBoutlist[[1]][,c(6)]  #get biomass for first case
    #  #Need to do some rounding before merging to lat longs match well enough
    #  #uKSpBout<-round(uKSpBout,digits=6)
    #  for (k in (2:length(cases))){
    #       uKSpBout<-merge(uKSpBout,uKSpBoutlist[[k]],by=c("Transect","Lat","Lon"),all=TRUE) #outer join
    #       #uKSpBout[is.na(uKSpBout)] <- 0 #change Nans to 0.
    #       colnames(uKSpBout)[colnames(uKSpBout)=='Agesum']<-cases[[k]]
    #       #uKSpBout[,cases[[k]]]<-uKSpBoutlist[[k]][,c(6)] #get biomass for other cases
    #  }
    #
    #  #Diff_uKSpBout<-uKSpBout[,c(1:5)] #keep metadata
    #  Diff_uKSpBout<-uKSpBout #keep metatdata, strata and total weight for each  (keep all)
    # # Diff_uKSpBout[,cases[[1]]]<-NULL  #get rid of original column.  Need to keep it for later calculations
    #  Diff_uKSpBout$wgt_total.x<-NULL #get rid of first weight total column
    #  Diff_uKSpBout$wgt_total.y<-NULL #get rid of second weight total column
    #  Diff_uKSpBoutGT0<-list()
    #  p<-list()
    #
    #  ## for >3 %
    #  for (k in (2:length(cases))){  #don't include difference of original from original in table
    #       Diff_uKSpBout[,cases[[k]]]<-uKSpBout[,cases[[k]]]
    #       Casepername<-paste0(cases[[k]],'%df')
    #       Diff_uKSpBout[,Casepername]<-100*(uKSpBout[,cases[[k]]]-uKSpBout[,cases[[1]]])/uKSpBout[,cases[[1]]]
    #       #p[[k]]<-filter(Diff_uKSpBout,.data[[cases[[k]]]]>0)%>% ggplot(aes(x=Lon,y=Lat, size=.data[[cases[[k]]]]))+
    #       p[[k]]<-filter(Diff_uKSpBout,abs(.data[[Casepername]])>3)%>% ggplot(aes(x=Lon,y=Lat, size=.data[[Casepername]]))+
    #            geom_point()
    #       #PLOT >3% difference
    #       Diff_uKSpBoutGT0[[k]]<-filter(Diff_uKSpBout,.data[[cases[[k]]]]!=0)  #outputs all non-zero for that case
    #  }
    #
    #  for (k in 2:length(cases)){
    #       pfname<-file.path(imagedirin,paste0(yearin,"_BM_Difference_map", hakeflagin,'.png'))
    #       p[[k]]  #plot
    #       ggsave(pfname)
    #  }

     return(list(uKSpBoutlist_diff,Sumdiffout))
}
