#' basic_BM_comps.R
#'
#' @description Function to compare two biomass estimates generated by Matlab
#'
#' @param SurveyName - name of survey
#' @param DirNameFile excel file - contains paths and locations of files. Uses
#'  Export_dir as the directory that the exported files are in.
#' @param sheet is an optional argument to denote which sheet of the DirNameFile
#' want to use. This defaults to the first sheet if not set.
#' @param hakeflag: adult hake age2+ (hakeflag=2), not filtering for hake (hakeflag=-1),
#'  age-0 hake (hakeflag=0), age-1 hake only (hakeflag=1), all hake (hakeflag=3), age-1+ (hakeflag=4).   Defaults to age2+
#' @examples
#'  \dontrun{
#' T<-basic_BM_comps(data,data2)
#'}
#' @export


basic_BM_comps<-function(SurveyNamein,DirNameFilein,imagedirin, case1in, case2in,hakeflagin=2,...){
     KBout<-read_proc_reports(SurveyNamein, DirNameFilein,case1in,hakeflag=hakeflagin) #kriged biomass outsputs for case 1
     KBout2<-read_proc_reports(SurveyNamein, DirNameFilein,case2in,hakeflag=hakeflagin)
     ## Make table of NASC and differences
     TotBio<-vector(length=2)
     TotBio[[1]]<-as.numeric(KBout[[1]])
     TotBio[[2]]<-as.numeric(KBout2[[1]])
     Per_diff=round(diff(TotBio)*100/TotBio[1],5)  #round to 5 decimal places
     TotBiotable<-data.frame(year,TotBio[1],TotBio[2],Per_diff)
     ftTotBio<-flextable::flextable(TotBiotable)
     ftTotBio<-flextable::set_header_labels(ftTotBio,TotBio.1.=case1in,TotBio.2.=case2in, Per_diff="Percent Difference")
     saveRDS(ftTotBio,file.path(imagedirin,paste0(year,"_export_BM_table")))
     return(list(KBout,KBout2,TotBiotable))
}
