#' compare_NASC_strata:  Read in report(s) generated by Matlab biomass estimation/kriging process
#'
#' @description Read in NASC tables for age-1+ full agemethods from two cases and compare
#' @param SurveyName - name of survey
#' @param DirNameFile excel file - contains paths and locations of files. Uses
#'  Export_dir as the directory that the exported files are in.
#' @param year
#' @param cases (cases to be compared - for right now, just compare 2)
#' @examples
#' temp<-compare_NASC_strata(SurveyName, DirNameFile,year,cases)
#'
#' @export
#'
compare_NASC_strata<-function(SurveyName, DirNameFile,year,cases=NULL,...){
     DirTable <- readxl::read_excel(DirNameFile, cases[[1]])  #load in directories/paths/ltocations
     DirTable_yr<- subset(DirTable, Survey ==SurveyName) #just year of interest
     DirTable_yr[] <- lapply(DirTable_yr, function(x) if(is.factor(x)) factor(x) else x)  #to ensure dataframe actually removed other variables in subset
     ReportBasePath<-as.character(DirTable_yr$Report_Base_Path[1])
     KrigingFilesPath<-file.path(ReportBasePath,'Kriging Files')  #sheet is the case in this case

     NASCbycase<-list()

     SheetPath<-file.path(KrigingFilesPath,cases[[1]])
     fbase<-c('detailsa')
     fbase<-glob2rx("*detailsa*") #https://stackoverflow.com/questions/18028225/r-list-files-with-multiple-conditions
     Fs<-list.files(file.path(SheetPath), pattern = fbase)  #
     fpbase<-file.path(SheetPath,Fs[2])  #don't have file open or won't work.  For the first case, original, read in age-2+ file.
     NASCbycase[[1]]<-readxl::read_excel(fpbase,1)  #read in sheet 3 for both male and female


     for (k in (2:length(cases))){
          SheetPath<-file.path(KrigingFilesPath,cases[[k]])
          fbase<-c('detailsa')
          fbase<-glob2rx("*detailsa*") #https://stackoverflow.com/questions/18028225/r-list-files-with-multiple-conditions
          Fs<-list.files(file.path(SheetPath), pattern = fbase)  #
          fpbase<-file.path(SheetPath,Fs[1])  #don't have file open or won't work.  Assumes the first file is the age-1+ file.
          NASCbycase[[k]]<-readxl::read_excel(fpbase,1)  #read in sheet 3 for both male and female
     }

     NASCbycase0<-NASCbycase[[1]]
     for (k in (2:length(cases))){
          NASCjoin<-merge(NASCbycase0,NASCbycase[[k]],by=c("Transect","VL start"),all=TRUE)#outerjoin
     }
     NASC_comp<-data.frame()
     NASCjoin$s_diff<-NASCjoin$Stratum.x-NASCjoin$Stratum.y
     NASCjoin$NASC_diff<-NASCjoin$NASC.x-NASCjoin$NASC.y
     NASCjoin_Origgt0<-dplyr::filter(NASCjoin,NASC.x>0) #just use those that originally had age-2+ fish in the interval
     SumNASC_Orig<-sum(NASCjoin_Origgt0$NASC.x)  #sum of original age-2+ fish
     NASCjoin_same_s<-dplyr::filter(NASCjoin_Origgt0,s_diff==0)
     NASCjoin_diff_s<-dplyr::filter(NASCjoin_Origgt0,s_diff!=0)
     NASC_comp[1,1]<-sum(NASCjoin_same_s$NASC_diff)/SumNASC_Orig
     NASC_comp[1,2]<-sum(NASCjoin_diff_s$NASC_diff)/SumNASC_Orig
     names(NASC_comp)=c("same_stratum","diff_stratum")
     return(list(NASCjoin,NASC_comp))
}
