#' read_proc_reports:  Read in report(s) generated by Matlab biomass estimation/kriging process
#'
#' @description Read in report(s) from Matlab biomass estimation from a directory
#' and calculate the total survey biomass estimate and biomass by age. Uses readxl
#' @param SurveyName - name of survey
#' @param DirNameFile excel file - contains paths and locations of files. Uses
#'  Export_dir as the directory that the exported files are in.
#' @param sheet is an optional argument to denote which sheet of the DirNameFile
#' want to use. This defaults to the first sheet if not set.
#' @param hakeflag: adult hake (hakeflag=2), not filtering for hake (hakeflag=-1), 
#' age-0 hake (hakeflag=0), age-1 hake only(hakeflag=1), all hake (hakeflag=3), age-1+ (hakeflag=4).  
#' set to 1 if want age1+ numbers, set to 0 (or other number) if want age2+.  Defaults to age2+

#' @examples
#' temp<-read_proc_reports(SurveyName, DirNameFile,sheet)
#'
#' @export
#'

read_proc_reports<-function(SurveyName, DirNameFile,sheet=NULL,hakeflag=2,...){

     DirTable <- readxl::read_excel(DirNameFile, sheet)  #load in directories/paths/ltocations
     DirTable_yr<- subset(DirTable, Survey ==SurveyName) #just year of interest
     DirTable_yr[] <- lapply(DirTable_yr, function(x) if(is.factor(x)) factor(x) else x)  #to ensure dataframe actually removed other variables in subset

     if (hakeflag==4){
          Exind<-43  #look here when age-1
          Agepath<-'Age1+'
     }else if (hakeflag==1){
          Exind<-42  #look here for age-1 only
          Agepath<-'Age1+'  #which directory to look at
     }else {
          Exind<-44  #look here for age-2+
          Agepath<-'Age2+'
     }
     
     #setup folders to read in data
     ReportBasePath<-as.character(DirTable_yr$Report_Base_Path[1])
     ReportYearPath<-file.path(ReportBasePath,'Reports',sheet,Agepath)  #sheet is the case in this case

     #read in kriged biomass @ age file
     fbase<-'kriged_len_age_biomass_table.xlsx'
     fpbase<-file.path(ReportYearPath,fbase)
     KBatAge<-readxl::read_excel(fpbase,3)  #read in sheet 3 for both male and female

     TotBio<-KBatAge[Exind,2]  #total biomass across all ages
     KBout<-list(TotBio)
     return(KBout)
}
