#' read_spat_unkriged_reports:  Read in report(s) generated by Matlab biomass estimation/kriging process
#'
#' @description Read in report(s) from Matlab biomass estimation from a directory
#' and calculate the total survey biomass estimate and biomass by age. Uses readxl
#' @param SurveyName - name of survey
#' @param DirNameFile excel file - contains paths and locations of files. Uses
#'  Export_dir as the directory that the exported files are in.
#' @param sheet is an optional argument to denote which sheet of the DirNameFile
#' want to use. This defaults to the first sheet if not set.
#' @param hakeflag. adult hake (hakeflag=2), not filtering for hake (hakeflag=-1),
#' age-0 hake (hakeflag=0), age-1 hake only (hakeflag=1), all hake (hakeflag=3), age-1+ (hakeflag=4).
#' @examples
#' \dontrun{
#' temp<-read_spat_unkriged_reports(SurveyName, DirNameFile,sheet,hakeflag=2)
#'}
#'
#' @export
#'

read_spat_unkriged_reports<-function(SurveyName, DirNameFile,sheet=NULL,hakeflag=2,...){

     DirTable <- readxl::read_excel(DirNameFile, sheet)  #load in directories/paths/ltocations
     DirTable_yr<- subset(DirTable, Survey ==SurveyName) #just year of interest
     DirTable_yr[] <- lapply(DirTable_yr, function(x) if(is.factor(x)) factor(x) else x)  #to ensure dataframe actually removed other variables in subset

     if (hakeflag==1){
          Colind<-c(6)  #look for these column when age-1
          Agepath<-'Age1+'
     }else if (hakeflag==4){
          Colind<-c(6:25)  #look here for age-1+
          Agepath<-'Age1+'  #which directory to look at
     }else {
          Colind<-c(7:25)  #look here for age-2+
          Agepath<-'Age2+'
     }

     #setup folders to read in data
     ReportBasePath<-as.character(DirTable_yr$Report_Base_Path[1])
     ReportYearPath<-file.path(ReportBasePath,'Reports',sheet,Agepath)  #sheet is the case in this case

     #read in kriged biomass @ age file
     fbase<-c('EchoPro_unkriged_aged_output*0.xlsx')
     fbase<-c("EchoPro_unkriged_aged_output*0\\.xlsx")
     fbase<-c("EchoPro_un-kriged_aged_output")
     Fs<-list.files(file.path(ReportYearPath), pattern = fbase)  #lists both the 0 and 1 - use the 0
     fpbase<-file.path(ReportYearPath,Fs[1])
     SpBatAge<-readxl::read_excel(fpbase,sheet=1)
     SpBatAge_names<-SpBatAge[1,]
     SpBatAge=SpBatAge[-1,]
     colnames(SpBatAge)<-SpBatAge_names
     SpB<-SpBatAge[,c(1:5)] #keep metadata
     SpB$Agesum<-rowSums(SpBatAge[,Colind])
     return(SpB)
}
