#' read_proc_reports_abund_cross:  Read in report(s) generated by Matlab biomass estimation/kriging process
#'
#' @description Read in report(s) from Matlab kriged abundance estimation from a directory
#' and calculate the total survey abundance estimate and abundance by age. Uses readxl
#' Is able to read in with separate method and hakeflag.
#'
#' @param SurveyName - name of survey
#' @param DirNameFile excel file - contains paths and locations of files. Uses
#'  Export_dir as the directory that the exported files are in.
#' @param sheet is an optional argument to denote which sheet of the DirNameFile
#' want to use. This defaults to the first sheet if not set.
#' @param hakeflag: adult hake (hakeflag=2), not filtering for hake (hakeflag=-1),
#' age-0 hake (hakeflag=0), age-1 hake only(hakeflag=1), all hake (hakeflag=3), age-1+ (hakeflag=4).
#' set to 1 if want age1+ numbers, set to 0 (or other number) if want age2+.  Defaults to age2+
#' @param method:  Can read in age-2+ biomass for either age-1+ method () or age-2+ method.
#' Cannot read in age-1 biomass for age-2+ method.  Method = 1 is for age-1+ method, method = 2
#' is for the age-2+ method.
#' @examples
#' temp<-read_proc_reports_cross(SurveyName, DirNameFile,sheet,hakeflag, method)
#'
#' @export
#'

read_proc_reports_abund_cross<-function(SurveyName, DirNameFile,sheet=NULL,hakeflag=2,method=1,...){

     DirTable <- readxl::read_excel(DirNameFile, sheet)  #load in directories/paths/ltocations
     DirTable_yr<- subset(DirTable, Survey ==SurveyName) #just year of interest
     DirTable_yr[] <- lapply(DirTable_yr, function(x) if(is.factor(x)) factor(x) else x)  #to ensure dataframe actually removed other variables in subset

     if (method==1){
          #Exind<-43  #look here when age-1
          Agepath<-'Age1+'
     }else if (method==2){
          #Exind<-42  #look here for age-1 only #CAN'T just take this number - is only
          #age-1's from aged fish.  For age1+ fish, the age2+ number isn't
          #calculated correctly - is age-2+ aged fish plus ALL unaged fish (including
          #those that would be apportioned to age-1.  Also applies to below
          Agepath<-'Age2+'  #which directory to look at
     }else {
          print("choose either method 1 (age1+) or method 2 (age2+)")
     }

     #setup folders to read in data
     ReportBasePath<-as.character(DirTable_yr$Report_Base_Path[1])
     ReportYearPath<-file.path(ReportBasePath,'Reports',sheet,Agepath)  #sheet is the case in this case

     #read in kriged abundance @ age file
     fbase<-'kriged_len_age_abundance_table.xlsx'
     fpbase<-file.path(ReportYearPath,fbase)
     KBatAge<-readxl::read_excel(fpbase,skip=1, sheet=3)  #read in sheet 3 for both male and female
     abundance <- as.data.frame(KBatAge[
               grepl("^[1-9]+", KBatAge$"0"),
               grepl("^[1-9]+", colnames(KBatAge))
               ])  #just the matrix
     abundance[] <- lapply(abundance, as.numeric)
     ArS<-rowSums(abundance)
     # make each row into proportion
     abundance_propbyrow<-apply(abundance, 2, function(data) data/ArS)  #take each row and divide it by the sum of the row
     nr<-nrow(abundance_propbyrow)
     # get subtotal column with total aged+unaged
     sub_tot_col<-KBatAge$Subtotal[1:nr]  #column with sum of aged and unaged fish at each length
     abundance_expanded<-apply(abundance_propbyrow,2,function(data) data*sub_tot_col) #take each row (which is a proportion) and times it by the subtotal
     patage_expanded<-colSums(abundance_expanded, na.rm=TRUE)  #the proportion at age of all fish, aged and unaged

     #this version skips the internal header row and uses the real headers
     # Use full matrix to proportion the unaged fish.
     if (hakeflag==4){
          TotBio<-sum(patage_expanded)  #look here when age-1+  #CAN'T just take this number - is only
          #age-1's from aged fish.  For age1+ fish, the age2+ number isn't
          #calculated correctly - is age-2+ aged fish plus ALL unaged fish (including
          #those that would be apportioned to age-1.  Also applies to below

     }else if (hakeflag==1){
          TotBio<-patage_expanded[1]  #look here for age-1 only

     }else {
          if (method==1){
               #age-1+ method
               TotBio<-sum(patage_expanded[-1])  #look here for age-2 with age-1+ method
          }else if (method==2){  #age-2+ method
               #matrix method above isn't how Chu calculated age-2+ method results - he used all of the unaged fish.
               #TotBio<-sum(patage_expanded[-1])  # age-2+
               Krownum<-43  #instead take number directly from results. Since this function explicitly uses the same
               #method as results (age-1+ method for age-1+ results and age-2+ methods for age-2+ results, this works here)
               #not bringing in first line, so different row number from some other methods
               TotBio<-KBatAge[Krownum,2]
          }else{
               print("unknown age method")
          }
     }

     KBout<-list(as.numeric(TotBio))
     return(KBout)
}
